apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: spark-tools-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/bfblog/spark-tools